name: flutter_modular_tests
description: A Flutter app showcasing some of my personal code written during tutorials or personal experiments!
repository: https://www.github.com/rcdevril/MyFlutterStudies.git

version: 0.1.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^0.4.1
  bloc: ^3.0.0
  responsive_builder: ^0.1.4
  get_it:
  json_serializable:
  provider_architecture:
  provider: ^3.1.0
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 1.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/img/icons/flutter_logo.png
